// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 99163f895057557b362154ec64acfcaf8cd98c477f79c0884555f347301f3c13
// Generated: 2026-05-12T12:19:57Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { RoleBinding, RoleBindingList, RoleBindingCreateRequest, RoleBindingPatchRequest } from './role_binding';

export class RoleBindingAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: RoleBindingCreateRequest, opts?: RequestOptions): Promise<RoleBinding> {
    return ambientFetch<RoleBinding>(this.config, 'POST', '/role_bindings', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<RoleBinding> {
    return ambientFetch<RoleBinding>(this.config, 'GET', `/role_bindings/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<RoleBindingList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<RoleBindingList>(this.config, 'GET', `/role_bindings${qs}`, undefined, opts);
  }
  async update(id: string, patch: RoleBindingPatchRequest, opts?: RequestOptions): Promise<RoleBinding> {
    return ambientFetch<RoleBinding>(this.config, 'PATCH', `/role_bindings/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/role_bindings/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<RoleBinding> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
